spring.application.name=HealthcareBackend

# AWS S3 Configuration
spring.cloud.aws.s3.bucket=bucket-name
spring.cloud.aws.region.static=us-east-1
# spring.cloud.aws.credentials.access-key=access-key
# spring.cloud.aws.credentials.secret-key=secret-key

