spring.application.name=HealthcareBackend

# AWS RDS (MySQL) Configuration
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# AWS S3 Configuration
spring.cloud.aws.s3.bucket=${S3_BUCKET_NAME}
spring.cloud.aws.region.static=${AWS_REGION}
# spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
# spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}

# Redis Cloud Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# OAuth2 Client Configuration (e.g., Google)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Enable Caching
spring.cache.type=redis
